Features/2 simple mvvm application
Nikita-Isaichenko/Programming pull request #6
Opened 2023-03-08 14:26 UTC by Nikita-Isaichenko

2023-03-08 15:08 UTC, OccVeneficus requested changes

2023-03-08 15:08 UTC, OccVeneficus commented on src/Contacts/Contacts/ViewModel/MainVM.cs
> +                return new RelayCommand((obj) =>
Каждый раз при вызове команды будет создаваться новый RelayCommand (вроде бы), т.е. свойство вычисляемое, хотя по сути в течении жизни программы обработчик команды не меняется. Вынеси инициализацию команд `Load` и `Save` в конструктор `MainVM`, и вместо того, чтобы прописывать лямбда выражения передавай приватные методы например 
`Load = new RelayCommand(LoadContact);`

2023-03-08 15:08 UTC, OccVeneficus commented on src/Contacts/Contacts/MainWindow.xaml
> +            <RowDefinition Height="31px"/>
В верстке избегай задания размеров grid точным значением. Либо "n*" либо "Auto"

2023-03-08 19:32 UTC, Nikita-Isaichenko commented on src/Contacts/Contacts/Model/Services/ContactSerializer.cs
> +            Contact? contact = new Contact();
Исправил

2023-03-08 19:32 UTC, Nikita-Isaichenko commented on src/Contacts/Contacts/Model/Services/ContactSerializer.cs
> +        /// создает экземпляр класса <see cref="ContactSerializer"/>.
Исправил

2023-03-08 19:32 UTC, Nikita-Isaichenko commented on src/Contacts/Contacts/MainWindow.xaml
> +                <TextBlock Text="PhoneNumber:" Margin="3px"/>
Исправил

2023-03-08 19:32 UTC, Nikita-Isaichenko commented on src/Contacts/Contacts/ViewModel/MainVM.cs
> +                return new RelayCommand((obj) =>
Исправил

2023-03-08 19:33 UTC, Nikita-Isaichenko commented on src/Contacts/Contacts/MainWindow.xaml
> +            <RowDefinition Height="31px"/>
Исправил

2023-03-09 01:38 UTC, OccVeneficus approved these changes

2023-03-09 01:39 UTC, merged